### PR TITLE
Enable building in OpenBSD

### PR DESCRIPTION
**Pull request by wsgac**
Hi,
I dabbled with your build script a bit and made it run under OpenBSD.

### CODE REVIEW

**Comment by wsgac** [comment]
I've noticed that tests fail for the setting `EVM_EMACS=emacs-git-snapshot-travis`. Looking at the output, I see that the problem there is with Cask missing. But it's external to Emacs. What should we do about this?

**Comment by wsgac** [comment]
Hi. Could you shed some light on whether this failure is caused by the build system or something in my code?

**Comment by wsgac** [comment]
Glad you could use it! There seems to be a problem with the automated
build, so I'm still waiting for it to be merged.

W dniu środa, 18 kwietnia 2018 joe di castro <notifications@github.com>
napisał(a):
> Thanks for this! I was able to compile it in OpenBSD with your changes.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/heWAYrjxEQD86cVTfyrZQtGIRSOE8ZvQpjROPBBflP1D9Hsd-UdiOVpsADuQ1Y5UWHleU4wN2fo8UpAdIxc-F-j2r3-f1_toKse-vi5vHFYb9nh9r_M907XvGybMnUjbNQLGGXVtLo1pP3SXflPGmFyLv0TWtw=s0-d-e1-ft#https://github.com/notifications/beacon/AAJZClJE31IWoThL0Cr0qVaQAFInmvYJks5tp1nigaJpZM4SAO0S.gif>

**Comment by politza** [comment]
Thanks.

Travis is broken again... Probably a problem with cask again, but I haven't looked into it.

**Pull request closed without merging**
