### PR TITLE
Fix compilation on OS X

### PR DESCRIPTION
**Pull request by gvol**
Hopefully, this fairly simple fix is acceptable upstream

### CODE REVIEW

**Comment by politza** [comment]
Ivan Andrus <notifications@github.com> writes:

> Hopefully, this fairly simple fix is acceptable upstream

Almost.

    diff --git a/Makefile b/Makefile
    [...]
    +#ifdef __APPLE__
    +#  define error printf
    +#endif

I don't understand this.  Are the signatures of error and printf equal
on OSX, seems that way ?

Would you mind rewriting this, since I don't suppose that printf on OSX
terminates the program ? Would something like the following ((which I
have used for a Windows port in a different project) work ?

    #define error(status, errno, fmt, args...)                      \
      do {                                                          \
        int error = (errno);                                        \
        fflush (stdout);                                            \
        fprintf (stderr, "%s: " fmt, PACKAGE_NAME, ## args);        \
        if (error)                                                  \
          fprintf (stderr, ": %s", strerror (error));               \
        fprintf (stderr, "\n");                                     \
        exit (status);                                              \
      } while (0)

**Comment by gvol** [comment]
Ah, very good.  I was blindly copying from Zheng Shao.  I tested that your definition behaves as expected (by adding internal_error(...) to main and seeing that it quit with error code 2.  

I took the liberty of making you the author of the commit.

**Comment by politza** [comment]
I'll merge it, but can you please move this define into the header
file (`epdfinfo.h`) ? I woule do it myself, but I'd like confirmation
that it still compiles.

Thanks.

**Comment by gvol** [comment]
Done.  Everything still compiles etc.  Thanks.

**Comment by zbeekman** [comment]
hmmm, I can’t seem to get this to build on OS X… I can’t figure out what I’ve done wrong

**Pull request merged**
