### PR TITLE
Ask user for a password if PDF is encrypted

### PR DESCRIPTION
**Pull request by lexa**
If user is trying to open encrypted file, password will be requested interactively.

This patch is related to issue #197

### CODE REVIEW

**Comment by lexa** [comment]
Hello, Would you mind merging this changes? They implement interactive password request for encrypted pdfs.

If you are not satisfied with this PR, please let me know.

**Comment by politza** [comment]
There are a couple of small problems, but a real problem is that you are
wrongly assume that `pdf-info-query' is always called with the current
buffer's filename as argument, i.e. the nil argument to `pdf-info-open'.
This would lead to a incomprehensible error message in case it is not,
e.g. a call like `(pdf-info-number-of-pages "foo.pdf")` in a *Help*
buffer.  Fixing this would require to basically analyze the arguments to
this function, which is ... not so good.

Also, I don't really like to do user-interaction in theses fairly
low-level functions.

Anyway, I implemented a different solution to this problem (branch
interactive-decryption).

Please tell me if this works for you and I'll merge it into master.

Thanks.

**Comment by lexa** [comment]
Thank you for your efforts. I've checked branch interactive-decryption. It works perfectly but there one minor issue. If I entered a password for the first time incorrectly, then a document fails to open. Could you please request for a password a few times?

**Comment by politza** [comment]
3a32d2420cc40ed864215f75aae4f6d868dc1cd2

**Comment by lexa** [comment]
Now It works perfectly, thank you.

**Comment by politza** [comment]
I think you're exaggerating. 

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Aleksei Fedotov <notifications@github.com> </div><div>Datum:30.01.2017  13:34  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Cc: politza <politza@fh-trier.de>,Comment <comment@noreply.github.com> </div><div>Betreff: Re: [politza/pdf-tools] Ask user for a password if PDF is encrypted
  (#215) </div><div>
</div>Now It works perfectly, thank you.

**Pull request closed without merging**
