### PR TITLE
Makefile(install-server-deps): add multi-distro support with auto-detection

### PR DESCRIPTION
**Pull request by ArneBab**
This adds dependency installation on Gentoo and provides a clear mechanism to extend this support for futher distributions.

### CODE REVIEW

**Comment by ArneBab** [comment]
The checks complain that the emacs-package let-alist* is missing — doesn’t look like it’s from my pull-request. Or did I miss something there?

**Comment by politza** [comment]
Travis was broken. I fixed it, but it is still somewhat fragile.

**Comment by ArneBab** [comment]
Do you need changes in this, or is the pull-request ready to go?

**Comment by politza** [comment]
First, this won't work, because there is still code in `pdf-tools.el` checking for `sudo` and `apt-get`.
Second, I'm not sure whether a simple mapping from package-tool to package-names is sufficient.
Third, I think it would be better to write a (or multiple) shell-script(s) dealing with the different systems. 

What do you think about that ?

**Comment by ArneBab** [comment]
I’m also not sure whether mapping from tool to packages will be sufficient, but I think it is very likely.

I think if there’s code in pdf-tools.el, then it would be better to not use a shell-script but to re-use the code in pdf-tools.el in the Makefile: Call pdf-tools.el (or something used by it) via emacs --batch …

**Comment by politza** [comment]
It seems that the package [`poppler`](https://packages.gentoo.org/packages/app-text/poppler) does not include the necessary glib component by default. Any idea how to solve this ?

**Comment by politza** [comment]
[autobuild](https://github.com/politza/pdf-tools/blob/master/server/autobuild)

**Comment by ArneBab** [comment]
does closing this mean you did solve it?

**Comment by politza** [comment]
Yes, see the comment above (and the one above that).

**Comment by politza** [comment]
Any idea regarding the emerge issue ?

**Comment by ArneBab** [comment]
Ich you can tell me which component is missing (i.e. which file), I can ask equery which package needs to be added.

**Comment by politza** [comment]
The closest would be `cairo`.  poppler comes with different front-ends  and we need the glib one (provides e.g. `poppler/glib/poppler-document.h`)  plus the "deprecated" header (`poppler/PDFDocEncoding.h`).  [This](https://github.com/politza/pdf-tools/commit/98a227bc1739e2a23b7ea84871974bd3ea5835ac) does not work currently.

**Comment by ArneBab** [comment]
yes, cairo pulls in glib, so that’s likely the useflag we need.

To enable it, there needs to be a command before the emerge:

`sudo euse -E -p app-text/poppler cairo`

**Comment by politza** [comment]
I opened an [issue](https://github.com/politza/pdf-tools/issues/316) for this.

**Pull request closed without merging**
