### PR TITLE
Update name of GooString::getCString to GooString::c_str

### PR DESCRIPTION
**Pull request by justbur**
See upstream poppler commit:

https://cgit.freedesktop.org/poppler/poppler/commit/goo/GooString.h?id=817b0f12453985c416a0388cdd4a09697d092b7f

### CODE REVIEW

**Comment by justbur** [comment]
It looks like the Travis build is using a different poppler version. I have 0.72.0 installed through homebrew on a mac, and `getCString` is gone in that version, so I couldn't build pdf-tools.

**Comment by politza** [comment]
You should define a macro conditioned on the poppler version.  Then use that macro in the code.  

We can't expect everyone to use the latest poppler version.

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Justin Burkett <notifications@github.com> </div><div>Datum:10.12.2018  15:48  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Cc: Subscribed <subscribed@noreply.github.com> </div><div>Betreff: Re: [politza/pdf-tools] Update name of GooString::getCString to
  GooString::c_str (#448) </div><div>
</div>It looks like the Travis build is using a different poppler version. I have 0.72.0 installed through homebrew on a mac, and getCString is gone in that version, so I couldn't build pdf-tools.

**Comment by justbur** [comment]
Yes of course. Please check that I did this correctly in 65af341

**Comment by politza** [comment]
It would be more readable and less redundant if you'd do something like this

    #if VERSIONTEST
    #define GET_CSTR c_str
    #else
    #define GET_CSTR GetCStr
    #endif

 and then use that macro in the code.

**Comment by justbur** [comment]
@politza fair enough. I squashed everything down into 581b65f. 

Thanks for the feedback. In case it's not obvious, I don't have much experience with c/c++.

**Comment by politza** [comment]
Thank you.

**Pull request merged**
