### PR TITLE
Recolor

### PR DESCRIPTION
**Pull request by oscarfv**
This is based on the `options` branch, which is not merged into `master` yet AFAIK.

One caveat with using `pdf-tools-setoptions` is that the change is not effective for the currently displayed page (if any). You need to redisplay the page somehow to see the changes. It works with the example added to `README.org` though, because the hook runs before the display.

### CODE REVIEW

**Comment by politza** [comment]
OK, great. I'll look into it, when I have the time.

oscarfv <notifications@github.com> writes:

> This is based on the options branch, which is not merged into master
> yet AFAIK.

Not fully, no.

> [...] You need to redisplay the page somehow to see the changes.

You can redisplay all visible pages of the current buffer like this:
(pdf-view-redisplay t) .

**Comment by politza** [comment]
I'm going to wrap it in a minor mode. Are white/black as fg/bg
reasonable default values for the colors ?

**Comment by oscarfv** [comment]
That is highly dependent on personal preferences. I myself use `#839496` for foreground and `#002b36` for background, which corresponds to the solarized dark theme and is very pleasant on low light conditions. In my experience, white on black quickly creates eye fatigue.

**Comment by politza** [comment]
oscarfv <notifications@github.com> writes:

> That is highly dependent on personal preferences. I myself use #839496
> for foreground and #002b36 for background, which corresponds to the
> solarized dark theme and is very pleasant on low light conditions. In
> my experience, white on black quickly creates eye fatigue.

So white on black would not be a good choice for most users.  It sounds
like the colors should default to the default's faces colors, no ?

**Comment by oscarfv** [comment]
That would work on my case. Dunno about others.

Please note that the main motivation for this feature is to allow pain-free night reading, so it makes little sense to use it with white-ish backgrounds and high contrast, as most Emacs themes have. In my case, on high light conditions I use solarized-light, but in that case I prefer no recolor.

As long as there is an easy method for disabling/enabling the feature and a discoverable way of customizing the bg/fg, the default is not super-important. Either the solarized-dark values I mentioned or using the default face would do, although the later is more difficult to implement because you need to know if the user already set his preferred values (which might coincide with the current theme) and deal with the case where the user changes the theme on the same Emacs session.

**Comment by politza** [comment]
oscarfv <notifications@github.com> writes:

> [...] the solarized-dark values [...]

It's not 'superimportant', but it's how almost all people discover this
feature for the first time.  So, I guess, I'm using the solarized-dark
values.

Would it make sense to use different colors, depending on the original
background of the PDF (i.e. incorporate pdf-view-dark-minor-mode) ? (I
haven't really looked at the filter algorithm).

**Comment by oscarfv** [comment]
How do we know the original background of the PDF? Either the page contains mostly text without a watermark, and in that case the background usually is white, or the page consists on a big image, and in that case the background can be anything, including a mix. I can't think of a method that can decide what's the right thing to do.

As mentioned before, the feature is geared towards night reading, hence we already have two modes of use: in low light we need recolor to avoid eye strain and in bright light we disable recolor to see the original page. Please note that seeing the original page is otherwise preferable because recolor does not play well with anything that is not text rendered on high-contrast bg/fg. That also means that it is important a quick method for enabling/disabling recolor, because some pages may contain elements which are not clearly visible after recolorizing, which forces the user to temporarily disable the feature. A keybinding would be nice for that.

**Comment by politza** [comment]
oscarfv <notifications@github.com> writes:

> How do we know the original background of the PDF? 

I've established that most colors (i.e. for isearching, the region) are
defined by faces.  This allows for the definition of 2 color pairs
(light/dark).  The idea is that, while most PDF's are black on white,
some may be whitish on blackish, like Emacs uses different colors
depending on the background mode.  This `background mode` of the PDF may
be changed with pdf-view-dark-minor-mode. (Check it out and press C-d
while isearching or C-c C-d otherwise.)

The question was whether this would make sense for the recoloring
also. (As I've said I haven't really looked at the algorithm and maybe I
should just do that.)

Now thinking about it, it probably wouldn't make much sense, since if
the background is already dark, it's already suitable for after midnight
reading.  But maybe it could also make sense the other way around,
i.e. lighten the image up.

Maybe I'm just giving this too much though ... ;-)

**Pull request merged**
