### PR TITLE
Adding `image-left` as a parameter to specify arrow positions in x-axis

### PR DESCRIPTION
**Pull request by ahmed-shariff**
Addition for the feature request in #582

### CODE REVIEW

**Comment by ahmed-shariff** [comment]
ping https://github.com/weirdNox/org-noter/issues/96

**Comment by vedang** [comment]
Hey @ahmed-shariff ,

Thanks for submitting this PR. I read through the conversation on #582, weirdNox/org-noter#96 and weirdNox/org-noter#129.

I'll need some more time to test out the changes on my own end and apply them, I will probably tackle this next weekend, I'm posting this update to let you know that I'm looking into it and hope to unblock `org-noter` for this change soon.

**Comment by vedang** [comment]
Hi @ahmed-shariff,

I experimented with this change on a two-column PDF paper, and there is a problem with it. Basically, if you take a precise note in the left column, but start from the end of the sentence instead of the start, then the placement of the tool-tip is confusing to the reader. This is because the tool-tip renders the _right arrow_ (→, "\u2192") character, but the reader is expecting the _left arrow_ to identify their note (←, "\u2190").

I expect this is the reason why @politza left out the x co-ord altogether and preferred the consistent experience of always using the y co-ord.

If you can think of a solution for this problem (what the direction of the arrow should be) that would work correctly in generic PDFs, please update this PR and let me know! The relevant code to show the tooltip is in the same function (`pdf-util-tooltip-arrow`)

**Comment by ahmed-shariff** [comment]
Hey @vedang, that you for the feedback.
I am not sure what you mean by the following?
> This is because the tool-tip renders the right arrow (→, "\u2192") character, but the reader is expecting the left arrow to identify their note (←, "\u2190").

Do you mean you were expecting the arrow to indicate which column the annotation belongs to?

Regarding the tootip showing up on top of the text, I agree it's confusing. I wanted to look at making the existing tooltip remain, while adding a marker to the precise location. Something like a red dot or a dashed line. I haven't gotten around to adding that. Will add to this PR when I get that working. 

If anyone has any other ideas, feel free to share.

**Comment by vedang** [comment]
> Do you mean you were expecting the arrow to indicate which column the annotation belongs to?

Yes, I mean that it should be easy for me to look at the tool tip and see the text I'm looking for. Currently, the tool tip misdirects me by pointing to a different space (in the example case I mentioned above)

**Pull request closed without merging**
