### PR TITLE
[WIP] Add new variable `pdf-view-scroll-slack`

### PR DESCRIPTION
**Pull request by nnicandro**
This variable allows for scrolling past the end of a page before switching to the next page. Addresses #434 and #437.

### CODE REVIEW

**Comment by politza** [comment]
I think this is a bit to technical.  The actual desirable feature is a predictable scroll up/down behavior.  I.e. scrolling the page once up and once down should be an identity operation.  Except for maybe at the end of the page.  Currently, doing this might display a different part of the PDF, in case scrolling reached the end of the current page.

**Comment by dzop** [comment]
Your right, it doesn't work as expected without additional configuration. I forgot that I had the following in my setup to update `next-screen-context-lines` dynamically based on window height. After removing the below configuration, it sometimes jumps to the next page without scrolling past the end first.

```emacs-lisp
(defvar pdf-view-scroll-window-fraction 0.8
  "The fraction of `window-height' used when scrolling a pdf.")

(defun pdf-view-maintain-window-context ()
  "Update window related variables on a change of the window configuration.

- Ensure that `next-screen-context-lines' is set to the
  `pdf-view-scroll-window-fraction' of `window-height' so that
  scrolling is consistent regardless of the size of the window."
  (when (eq major-mode 'pdf-view-mode)
    (setq-local next-screen-context-lines
                (ceiling (* (window-height) pdf-view-scroll-window-fraction)))))

(defun nn/pdf-view-mode-hook ()
  (pdf-view-maintain-window-context)
  (add-hook 'window-configuration-change-hook
            'pdf-view-maintain-window-context nil t))

(add-hook 'pdf-view-mode-hook #'nn/pdf-view-mode-hook)
```

I think if you add the above configuration you will get the desired result that this patch is trying to achieve. Maybe we can add in this dynamic updating of `next-screen-context-lines` as well?

**Comment by dzop** [comment]
It looks like there would still be some interaction between `pdf-view-scroll-window-fraction` and `pdf-view-scroll-slack` that will lead to undesirable behavior. Maybe it can be done with one variable, e.g. keep `pdf-view-scroll-window-fraction` and then base `pdf-view-scroll-slack` off of it.

**Comment by politza** [comment]
I was'nt actually trying.

I was trying to express that there should be a on/off option and the rest be implementation detail.




<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Nathaniel Nicandro <notifications@github.com> </div><div>Datum:13.04.2019  22:35  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Cc: politza <politza@fh-trier.de>,Comment <comment@noreply.github.com> </div><div>Betreff: Re: [politza/pdf-tools] [WIP] Add new variable
  `pdf-view-scroll-slack` (#481) </div><div>
</div>Your right, it doesn't work as expected without additional configuration. I forgot that I had the following in my setup to update next-screen-context-lines dynamically based on window height. After removing the below configuration, it sometimes jumps to the next page without scrolling past the end first.

(defvar pdf-view-scroll-window-fraction 0.8
  "The fraction of `window-height' used when scrolling a pdf.")

(defun pdf-view-maintain-window-context ()
  "Update window related variables on a change of the window configuration.

- Ensure that `next-screen-context-lines' is set to the
  `pdf-view-scroll-window-fraction' of `window-height' so that
  scrolling is consistent regardless of the size of the window."
  (when (eq major-mode 'pdf-view-mode)
    (setq-local next-screen-context-lines
                (ceiling (* (window-height) pdf-view-scroll-window-fraction)))))

(defun nn/pdf-view-mode-hook ()
  (pdf-view-maintain-window-context)
  (add-hook 'window-configuration-change-hook
            'pdf-view-maintain-window-context nil t))

(add-hook 'pdf-view-mode-hook #'nn/pdf-view-mode-hook)
I think if you add the above configuration you will get the desired result that this patch is trying to achieve. Maybe we can add in this dynamic updating of next-screen-context-lines as well?

**Comment by dzop** [comment]
Oh OK. The behavior is the same as without this change when `pdf-view-scroll-slack` is 0, which is the default value. But I'll see if I can refactor to make what its doing more obvious.

**Comment by munterkalmsteiner** [comment]
@dzop, this feature would be very nice! It seems to be a better solution to what I suggested [here](https://emacs.stackexchange.com/questions/59567/pdfview-scroll-line). Do you have any plans to get this merged?

**Pull request closed without merging**
