### PR TITLE
Small changes to fix build on FreeBSD and OpenBSD

### PR DESCRIPTION
**Pull request by Jehops**

### CODE REVIEW

**Comment by politza** [comment]
Never mind. I wrote a configure check for this.

**Comment by Jehops** [comment]
Ah yes.  That's a typo.

**Comment by politza** [comment]
Can you please pull and verify that it builds on BSD ?

**Comment by Jehops** [comment]
politza <notifications@github.com> writes:
> Can you please pull and verify that it builds on BSD ?

Confirmed.  It does build without error on FreeBSD.

**Comment by politza** [comment]
Thanks.

**Pull request closed without merging**
