### PR TITLE
Add Windows compilation instructions

### PR DESCRIPTION
**Pull request by tuhdo**
We should let Windows users enjoy this awesome package as well.

`pdf-tools`  rocking on Windows:

pdf_tools_window

`pdf-tools` successfully compiled:

pdf_tools_window_compilation

### CODE REVIEW

**Comment by politza** [comment]
So this will only work with Cygwin/Emacs, right ?

**Comment by tuhdo** [comment]
Yes. I only managed to get Cygwin to build `pdf-tools`.

**Comment by a-fent** [comment]
My guess would be that for most users, the "native" versions of Emacs are preferable to the Cygwin ones on Windows (faster, no "`/cygdrive`"). I followed [someone else's instructions](https://gist.github.com/justbur/afb5f605def2376eeffc643f7b7daae9) for compiling pdf-tools using MSys2. These worked perfectly and I know have a pdf-tools that works with precompiled native Emacs 25.1 available online.

Would a revised patch incorporating these instructions be welcome?

**Comment by politza** [comment]
Yes, that would be useful.

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Alex Fenton <notifications@github.com> </div><div>Datum:10.03.2017  11:53  (GMT+01:00) </div><div>An: politza/pdf-tools <pdf-tools@noreply.github.com> </div><div>Cc: politza <politza@fh-trier.de>,Comment <comment@noreply.github.com> </div><div>Betreff: Re: [politza/pdf-tools] Add Windows compilation instructions (#218) </div><div>
</div>My guess would be that for most users, the "native" versions of Emacs are preferable to the Cygwin ones on Windows (faster, no "/cygdrive"). I followed someone else's instructions for compiling pdf-tools using MSys2. These worked perfectly and I know have a pdf-tools that works with precompiled native Emacs 25.1 available online.

Would a revised patch incorporating these instructions be welcome?

**Comment by politza** [comment]
I tried (not very hard) the mentioned instructions, but it didn't work.  It compiles,
but won't run, neither in ming64 nor in cmd.exe, due to missing dll's.

It seems there are some dependencies missing.

-ap

**Comment by politza** [comment]
Done.

**Pull request closed without merging**
